---
- name: Create ec2 instance
  ec2:
    key_name: aws_user
    instance_tags: {"name":"webserver","env":"dev"}
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ec2_ami}}"
    wait: yes
    group: "{{ sg_name }}"
    count: 1
    region: "{{ vpc_region }}"
    vpc_subnet_id: "{{ vpc.subnets[0].id}}"
    assign_public_ip: yes

- name: Refresh inventory
  meta: refresh_inventory
